prototype/high-fedility/config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mains#landing', as: 'landing'

  get '/register', to: 'users#new', as: 'register'
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/activate', to: 'users#activate', as: 'activate'
  put '/activate', to: 'users#activated', as: 'activated'
  put '/regerate', to: 'users#regenerate_code', as: 'regenerate_code'

  put '/courses/:course_id/enroll', to: 'courses#enroll', as: 'course_enroll'
  put '/courses/:course_id/posts/:post_id/award', to: 'posts#award', as: 'course_post_award'
  put '/courses/:course_id/posts/:post_id/comments/:comment_id/award', to: 'comments#award', as: 'course_post_comment_award'

  resources :sessions, only: [:create]
  resources :users, except: [:new]

  resources :courses do
    resources :posts do
      resources :comments
    end
  end

end

prototype/high-fedility/app/models/comment.rb
class Comment < ApplicationRecord
    validates_presence_of :body

    has_ancestry

    belongs_to :post
    belongs_to :user
    
    has_many :awards, dependent: :destroy

    def awards_to_s
        return "Trophies: #{self.awards.where(award_type: 1).count} | Medals: #{self.awards.where(award_type: 0).count}"
    end

    def award_bool_to_s(user)
        if self.awards.find_by(backer: user).nil?
            return "Reward"
        else
            return "Unreward"
        end
    end

end

prototype/high-fedility/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in?

  before_action :get_course
  before_action :get_post
  before_action :set_comment, only: %i[show edit update destroy award]

  before_action :can_modify?, only: %i[edit update]
  before_action :can_delete?, only: %i[destroy]

  before_action :awardable?, only: %i[award]

  def index
    @comments = @post.comments
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:success] = "true"
      flash[:message] = "Successfully left a comment."
      redirect_to course_post_path(@course, @post)
    else
      flash[:success] = "false"
      flash[:message] = "An error occured while leaving a comment. Please try again."
      flash[:errors] = @comment.errors
      redirect_to new_course_post_comment_path
    end
  end

  def update
    params[:comment][:parent_id] = @comment.parent_id
    if @comment.update(comment_params)
      flash[:success] = "true"
      flash[:message] = "Successfully updated the comment"
      redirect_back(fallback_location: course_post_path(@course, @post))
    else
      flash[:success] = "false"
      flash[:message] = "An error occured while updating a comment. Please try again."
      redirect_to edit_course_post_comment_path
    end
  end

  # DELETE /comments/1
  def destroy
    flash[:message] = "Comment has been deleted."
    @comment.destroy
    redirect_to course_post_path(@course, @post)
  end

  def award
    @comment.user.toggle_reward(current_user, nil, @comment)
    redirect_back(fallback_location: course_post_path(@course, @post))
  end

  private
    def set_comment
      if params[:id]
        @comment = Comment.find(params[:id])
      else
        @comment = Comment.find(params[:comment_id])
      end
    end

    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end

    def get_course
      @course = Course.find(params[:course_id])
    end

    def get_post
      @post = Post.find(params[:post_id])
    end

    def can_modify?
      not_found unless @comment.user == current_user
    end

    def can_delete?
      not_found unless @comment.user == current_user or !current_user.student?
    end

    def awardable?
      redirect_back(fallback_location: course_post_path(@course, @post)) if @comment.user == current_user
    end

end

prototype/high-fedility/app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end
end

prototype/high-fedility/app/views/comments/_comment.haml
.fw-bold
  = comment.user.full_name_to_s
.fw-light
  = comment.awards_to_s
%div
  = comment.body
.nav
  .col
    .d-flex.float-start
      %button.btn.btn-link.btn-sm.text-decoration-none{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{new_course_post_comment_path(@course, @post, :parent_id => comment, :yeild_only => true)}', 'ajax_content')"} Reply
      - if comment.user != current_user
        #{button_to comment.award_bool_to_s(current_user), course_post_comment_award_path(@course, @post, comment), method: :put, :class => "btn btn-link btn-sm text-decoration-none"}
      - if comment.user == current_user
        %button.form.btn.btn-link.btn-sm.text-decoration-none{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :onclick => "ajax_get_page('GET', '#{edit_course_post_comment_path(@course, @post, comment, :yeild_only => true)}', 'ajax_content')"} Edit
      - if comment.user == current_user or !current_user.student?
        #{button_to "Delete", [@course, @post, comment], method: :delete, :class => "btn btn-link btn-sm text-decoration-none"}

prototype/high-fedility/app/views/comments/_form.haml
= form_with(model:[@course, @post, comment]) do |form|
  .modal-dialog
    .modal-content
      .modal-header.text-center
        %h4.modal-title.w-100.font-weight-bold #{action_name.capitalize} Comment
      #c_form-h.m-3
        .row
          .col-sm.fw-bold
            Descrtiption
        %br/
        .row
          .col-sm
            = form.text_area :body, class:"form-control", rows:"5", placeholder:"Enter your comment description..."
            = form.hidden_field :parent_id, value: params[:parent_id]
      .modal-footer.d-flex.justify-content-center
        = submit_tag "Submit", class:"btn btn-default modal-title w-100 font-weight-bold"

prototype/high-fedility/app/views/comments/edit.haml
= render "form", comment: @comment

prototype/high-fedility/app/views/comments/index.haml
.nav
  .col
    .d-flex.float-start
      %h3 Comments
  .col 
    .d-flex.float-end
      - if defined? post_id
        %button.btn.btn-primary.fs-6.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{new_course_post_comment_path(:post_id => post_id, :yeild_only => true)}', 'ajax_content')"} New Comment
      - else
        %button.btn.btn-primary.fs-6.fw-bold{"data-bs-target" => "#ajax_popup", "data-bs-toggle" => "modal", :id => "", :onclick => "ajax_get_page('GET', '#{new_course_post_comment_path(:yeild_only => true)}', 'ajax_content')"} New Comment
%br/
.card
  .card-body
    = nested_comments(@post.comments.arrange)

prototype/high-fedility/app/views/comments/new.haml
= render "form", comment: @comment

prototype/high-fedility/app/views/comments/show.haml
= render @comment